// docgen.ts
// Write-back actually stamps each affected doc with a regeneration marker, so a
// reviewer can SEE the docs update after a change is approved. (In production
// this is where Oynix regenerates the doc content; here we stamp a timestamp.)

import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";

const MARKER_RE = /^> 🔄 _Regenerated by Oynix Guardian.*_$/m;

/** Stamp each affected doc with a fresh regeneration marker. Returns the list. */
export function regenerateDocs(
  repoRoot: string,
  docs: string[],
  prNumber: number | null
): string[] {
  const stamp =
    `> 🔄 _Regenerated by Oynix Guardian — ${new Date().toISOString()}` +
    (prNumber ? ` (PR #${prNumber})_` : `_`);
  const updated: string[] = [];

  for (const rel of docs) {
    const full = join(repoRoot, rel);
    if (!existsSync(full)) continue;
    let text = readFileSync(full, "utf8");

    if (MARKER_RE.test(text)) {
      text = text.replace(MARKER_RE, stamp); // refresh existing stamp
    } else {
      const lines = text.split("\n");
      const headingIdx = lines.findIndex((l) => l.startsWith("# "));
      const at = headingIdx >= 0 ? headingIdx + 1 : 0;
      lines.splice(at, 0, "", stamp); // insert under the title
      text = lines.join("\n");
    }
    writeFileSync(full, text);
    updated.push(rel);
  }
  return updated;
}
